name: Discord Push Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord message
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_AVATAR: ${{ github.event.head_commit.author.avatar_url }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH: ${{ github.ref_name }}
        run: |
          if [ -z "$COMMIT_AVATAR" ]; then
            COMMIT_AVATAR="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          fi

          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-7)
          COLOR=10181046

          payload=$(cat <<EOF
          {
            "username": "GitHub",
            "embeds": [{
              "author": { "name": "New Commit", "icon_url": "$COMMIT_AVATAR" },
              "description": "$COMMIT_MESSAGE",
              "fields": [
                { "name": "Commit", "value": "\`$SHORT_SHA\`", "inline": true },
                { "name": "Branch", "value": "\`$BRANCH\`", "inline": true }
              ],
              "color": $COLOR,
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            }]
          }
EOF
)

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "$WEBHOOK_URL"
